### ISSUE TITLE
Error when running pyFAT with an existing sofia2 catalogue option

### ISSUE THREAD

**Issue by 3rico** [SoFiA-Admin/SoFiA-2#54]
On setting 
fitting:
  catalogue_start_id: '-1'
  catalogue_end_id: '-1'
  fitting_stages:
  - create_fat_cube
  - Sofia_Catalogue
  - Existing_Sofia
  - Fit_Tirific_OSC

And running pyFAT, i stumble upon an error that requires the preious sofia2 run having produced nchan maps per cubelets. But it is my understanding that sofia2 does not make these channel maps but instead makes one channel map for the entire field. Is it possible to configure pyFAT to take as input the(bigger) channel map fits file? until sofia2 makes these channel maps per cubelet? 

`cp: cannot stat '/home/maina/vault-ike/PKS_2020_Abhisek/Full_cube/sofia_tclean_image_4_beam_corrected_flipped_channels/tclean_image_4_beam_corrected_flipped_channels_cubelets/tclean_image_4_beam_corrected_flipped_channels_1_chan.fits': No such file or directory
Traceback (most recent call last):
  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 157, in main
    Full_Catalogue = rf.sofia_input_catalogue(Original_Configuration)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/read_functions.py", line 1210, in sofia_input_catalogue
    copy_homemade_sofia(Configuration,no_cat=True,debug=False)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/support_functions.py", line 781, in copy_homemade_sofia
    hdr = clean_header(Configuration,hdr_in,two_dim=two_dim,mask_file=mask_file,debug=debug)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/support_functions.py", line 303, in clean_header
    for line in hdr['HISTORY']:
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/astropy/io/fits/header.py", line 143, in __getitem__
    return _HeaderCommentaryCards(self, key)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/astropy/io/fits/header.py", line 2220, in __init__
    self._count = self._header.count(self._keyword)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/astropy/io/fits/header.py", line 1364, in count
    raise KeyError(f"Keyword {keyword!r} not found.")
KeyError: "Keyword 'HISTORY' not found."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/ipdb/__main__.py", line 305, in main
    pdb._runscript(mainpyfile)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/brenda/anaconda3/envs/py37/bin/pyFAT", line 3, in <module>
    __requires__ = 'pyFAT-astro==0.0.8'
  File "/home/brenda/pyFAT-astro/bin/pyFAT", line 7, in <module>
    main.main(sys.argv[1:])
  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 414, in main
    Configuration['FINAL_COMMENT'] = e
UnboundLocalError: local variable 'Configuration' referenced before assignment
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
`

**Comment by paoloserra** [comment]
We've discussed your issue and have agreed to add the `nrchan` 2D image per source back to the list of output products that users can write to disc. Stay tuned for that change.

**Comment by SoFiA-Admin** [comment]
Thank you, @3rico, for reporting this problem. I have modified the code such that by default both the number of channels and the SNR cubes are generated for all individual sources. This should resolve the incompatibility with pyFAT. Please try installing and running the latest version of SoFiA (https://github.com/SoFiA-Admin/SoFiA-2/archive/refs/heads/master.zip) and let me know if that resolves the issue.

**Comment by 3rico** [comment]
That solved it thank you!!

**Comment by SoFiA-Admin** [comment]
Excellent! I will close this issue now. Please feel free to open a new issue if you encounter any other problems with SoFiA.
